---
title:  "예외처리"

categories:
  - JAVA
tags:
  - JAVA
  - Exception
  - ERROR
comments: true
---
## 에러의 종류

1. 컴파일 에러 : 컴파일 시에 발생하는 에러
2. 런타임 에러 : 실행 시에 발생하는 에러
3. 논리적 에러 : 실행이 되는데 의도와 다르게 동작하는 경우

런타임 에러를 두가지로 구분한다.
1. 에러 : 코드에 의해서 수습될 수 없는 심각한 오류
2. 예외 : 코드에 의해서 수습할 수 있는 미약한 오류


## 예외 클래스 구조
모든 예외의 최고 조상은  `Exception` 클래스이며 그 안에 `RuntimeException`가 있다.
예외 클래스는 크게 위 두개로 나뉜다.

`RuntimeException`클래스는 주로 프로그래머의 실수에 의해 발생 할 수 있는 예외들과 관련있고,(unchecked예외, 컴파일러가 예외처리를 확인하지않음)
`Exception`클래스는 주로 외부의 영향(사용자의 실수)으로 발생 할 수 있는 예외들과 관련있다.(checked예외, 컴파일러가 예외처리를 확인함. 예외처리안하면 컴파일에러)

## 예외처리하기
### try-catch 구문
```java
try{
	//예외가 발생할 가능성이 있는 코드
}catch(Exception1 e1){
	//Exception1 예외가 발생했을 경우 처리하는 코드
}catch(Exception2 e2){
	//Exception2 예외가 발생했을 경우 처리하는 코드
}
```
#### 에러예시
```java
class ExceptionEx2 {
	public static void main(String args[]) {
		int number = 100;
		int result = 0;

		for(int i=0; i < 10; i++) {
			result = number / (int)(Math.random() * 10); // 7번째 라인, 0으로 나누게 되어 ArithmeticException이 발생 할 수 있음.
			System.out.println(result);
		}
	}
}
```
결과
```
20
100
java.lang.ArithmeticException: / by zero at ExceptionEx2.main(ExceptionEx2.java:7)
```
#### 예외처리
```java
class ExceptionEx3 {
	public static void main(String args[]) {
		int number = 100;
		int result = 0;

		for(int i=0; i < 10; i++) {
			try {// 에러가 생길수 있는 코드 입력
				result = number / (int)(Math.random() * 10);
				System.out.println(result);
			} catch (ArithmeticException e)	{ // ArithmeticException이 발생되면 실행되는 코드
				System.out.println("0");
			}  
		}
	}
}
```
- ArithmeticException이 아닌 Exception 클래스를 사용해도 가능하다 (Exception이 더 상위 클래스)

```java
catch(ExceptionA | ExceptionB) {
	//이렇게 | 를 이용해서 멀티catch블럭 생성가능
}
```
## 예외 처리 흐름

- try블럭에서 예외가 발생한 경우
발생한 예외와 일치하는 catch블럭으로 이동 후 catch구문 수행 후 try-catch를 빠져나오고 계속 진행.
일치하는 catch블럭을 찾지못하면 예외는 처리되지 않음.

- try블럭에서 예외가 발생하지 않은경우
try-catch를 빠져나오고 계속 진행.

## 자주쓰는 예외 관련 메서드
printStackTrace() 예외발생 당시의 호출스택에 있었던 메서드의 정보와 메시지를 출력.
getMessage()  발생한 예외클래스의 인스턴스에 저장된 메시지를 얻음.

## 메서드에 예외선언
